import pygame as pg
LINHAS = 8
COLUNAS = 13
TAMANHO_QUADRADO = 32
TAMANHO_ICONES = 16
MULTI = 2
TELA_LARGURA = TAMANHO_QUADRADO * COLUNAS * MULTI
TELA_ALTURA = TAMANHO_QUADRADO * LINHAS * MULTI
FPS = 60
COLDOWNANIMATION = 15

ENEMYEVENT = pg.USEREVENT + 1

bandeiraClicado = None
