LINHAS = 8
COLUNAS = 12
TAMANHO_QUADRADO = 32
TAMANHO_ICONES = 16
OFF_SET = 4
TELA_LARGURA = TAMANHO_QUADRADO * COLUNAS
TELA_ALTURA = TAMANHO_QUADRADO * LINHAS
PAINEL = ((TAMANHO_ICONES * 2) + (OFF_SET*3))
FPS = 60

bandeiraClicado = None